const EErrors = {
  ROUTING_ERROR: 1,
  INVALID_TYPES_ERROR: 2,
  DATABASE_ERROR: 3,
  ADD_PRODUCT_ERROR: 4,//
  EDITING_PRODUCT_ERROR:5,//
  DUPLICATE_CODE_ERROR: 6,//
  DELETING_PRODUCT_ERROR:7,//
  LOGIN_ERROR: 8,//
  ADDING_PRODUCT_TO_CART_ERROR: 9,
};
  
export default EErrors